### ISSUE TITLE
Can't perform login in local server

### ISSUE THREAD

**Issue by gabrielmarques0** [rtkg12/remixr#5]
Hey, I tried to run the project locally, but the login doesn't seem to work. I noticed that the `access_token` and `refresh_token` cookies are not present in the local storage after login. It seems to be related to this option added to the cookies:
`secure: true` (apiRoutes.js:48)

When I removed it, the login worked fine

**Comment by rtkg12** [comment]
Hi @GabrielGAM25, thanks for pointing that out! I just added the extra parameters for cookies earlier this week and haven't tested in much in a development environment. I think conditionally removing the secure, domain and sameSite options for the cookies in a non-prod environment should resolve the issue as these are just present to make it more secure in production. 

You're free to take up this issue and submit a PR if you'd like. If not, I'll fix it in a couple of days. If you need any help getting started, please feel free to let me know.

**Comment by soujanyachan** [comment]
Hi, I would like to work on this issue. Could you guide me on how to test out that the changes I have made are as required?

I made the changes and tested locally, I am able to login without an issue. 

PR Link: https://github.com/rtkg12/remixr/pull/7

I was also wondering if I could create a PR fixing some of the ESLint issues?

**Comment by rtkg12** [comment]
@soujanyachan Thanks for taking this up. I will review your PR as soon as possible.

About the ESLint issues, I was planning on creating an issue for that. I'll do that now and assign it to you if you want to work on that.

**Comment by soujanyachan** [comment]
@rtkg12 yes, you can assign the ESLint issue to me. Thanks!
